services:
  - type: worker
    name: quizbot
    env: python
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false     # секрет добавим в Render после создания сервиса
      - key: DB_PATH
        value: /data/quizbot.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
